### ISSUE TITLE
Incomplete documentation for function load_tiger in tiger_xwalk.py

### ISSUE THREAD

**Issue by windnage** [mgraber/tiger_maf_xwalk#5]
@mgraber The function load_tiger in tiger_xwalk.py has incomplete documentation for the inputs and outputs. I'm not sure what edge_path and face_path should be -- both the format and what they are. 
I don't know what edges and faces outputs are that the function returns. An explanation of these would be really helpful.

Thanks!
Ann

**Comment by mgraber** [comment]
Thanks @windnage. I completed the documentation of inputs and outputs for load_tiger, as well as load_tiger_csv. I included explanation about how they differ.
